### ISSUE TITLE
Very strange when requesting a non exsting date from archive get debug page even w debug off

### ISSUE THREAD

**Issue by dartdog** [montylounge/django-mingus#21] opened 2009-12-02 22:52 UTC
Another item I've been trying to track down is some errors from the error log
when something hits my site requesting items from too far back I get a Django Debug error page rather than the nice page does not exist that you have in the normal flow, I have all debug set to false.. and this is the only condition that gives me the problem example: http://oswco.org/2009/jul/31/

other errors/ not founds work fine.. Again I'm looking and if I find I'll report back but pointers appreciated.

**Comment by montylounge** [comment] 2009-12-04 04:38
I'll take a look and try and post a fix shortly. thanks!

**Comment by montylounge** [comment] 2010-01-15 13:05
Any update?

**Comment by montylounge** [comment] 2010-01-19 03:34
Closing. Can't reproduce.

**Closed as completed by montylounge** 2010-01-19 03:34 UTC
