### ISSUE TITLE
error on ubuntu and postgresql

### ISSUE THREAD

**Issue by binarymatt** [montylounge/django-mingus#29] opened 2010-01-27 23:33 UTC
I was trying to create a mingus install on my slicehost and I kept getting the following error when running syncdb:
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block

I tracked it down to the commit: 2979ea3d4541f7b3c51c17e160bc95b468ac999b
If I reset back to commit 2f7eb8de7e2cb1c776e801a40f008048fcbb6d36, syncdb works fine, but the minute I step forward to the commit above, i get the transaction error.

This might help as well, the following query is showing up when I run ./manage.py syncdb in my postgres logs:

ERROR:  relation "django_site" does not exist at character 78
STATEMENT:  SELECT "django_site"."id", "django_site"."domain", "django_site"."name" FROM "django_site" WHERE "django_site"."id" = 1  ORDER BY "django_site"."domain" ASC

**Comment by montylounge** [comment] 2010-01-28 01:02
Hmm. Thanks for filing the issue. I'll look into resolving asap.

**Comment by montylounge** [comment] 2010-01-28 01:08
From a quick look at the issue, the above reminds me of ticket I filed with django-request a few weeks back: http://github.com/kylef/django-request/issues/closed#issue/12

The author merged a commit I provided to resolve the issue, but maybe it's been re-introduced. I'll take a look again. 

Thanks again for filing the bug.

**Comment by montylounge** [comment] 2010-01-28 01:59
Waiting on binarydud to confirm a few things for me that I messaged him to confirm. 

For now I think the issue is no longer a bug on HEAD, just an issue with the commit he's on locally. But let's wait out to confirm before I close it out.

**Comment by tgautier** [comment] 2010-01-28 03:46
I have the same problem with postgresql8.4.2 using the latest mingus rev when executing a syncdb on a clean virtualenv with python 2.5.2

**Comment by tgautier** [comment] 2010-01-28 03:54
When going back to use sqlite3 I get the following error: 
OperationalError: no such table: django_site

I've executed the following steps with no error:
./manage.py syncdb
./manage.py loaddata fixtures/test_data.json

Note that when using the internal server it works just fine, but not with my apache2+mod_wsgi setup.

**Comment by montylounge** [comment] 2010-01-28 15:37
Ok, I'll dive into it tonight. Sorry for the inconvenience.

**Comment by montylounge** [comment] 2010-01-28 23:51
Found the issue. It's related to django-request and postgres. I'll get a fix out tonight.

**Comment by montylounge** [comment] 2010-01-29 04:22
Updated both stable-requirements and requirements to pull from my fork of django-request.  Tested on PostgreSQL 8.3.7 and Ubuntu Intrepid.

Please pull form master HEAD.

**Closed as completed by montylounge** 2010-01-29 04:22 UTC
